import { RoomResponseDto } from "../../types/dto/RoomResponse.dto";

export const testRoomSet: RoomResponseDto[] = [
  {
    id: 1,
    name: "Стандартный номер",
    description: "Уютный номер с одной кроватью и видом во двор",
    capacity: 2,
    price: "2500.00",
    status: "available",
    area: 20,
    Image: [
        {
          id: 101,
          fileName: "room1-1.jpg",
          url: "https://example.com/images/room1-1.jpg",
          path: "/uploads/room1-1.jpg",
          roomId: 1,
        },
        {
            id: 102,
            fileName: "room1-2.jpg",
            url: "https://example.com/images/room1-2.jpg",
            path: "/uploads/room1-2.jpg",
            roomId: 1,
          },
      ],
  },
  {
    id: 2,
    name: "Делюкс",
    description: "Просторный номер с king-size кроватью",
    capacity: 2,
    price: "4500.00",
    status: "available",
    area: 35,
    Image: [
      {
        id: 201,
        fileName: "room2-1.jpg",
        url: "https://example.com/images/room2-1.jpg",
        path: "/uploads/room2-1.jpg",
        roomId: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Семейный номер",
    description: "Номер с двумя раздельными кроватями и дополнительным местом",
    capacity: 4,
    price: "6000.00",
    status: "booked",
    area: 42,
    Image: [],
  },
  {
    id: 4,
    name: "Люкс",
    description: "Роскошный номер с гостиной зоной и джакузи",
    capacity: 2,
    price: "8500.00",
    status: "available",
    area: 55,
    Image: [
      {
        id: 401,
        fileName: "room4-1.jpg",
        url: "https://example.com/images/room4-1.jpg",
        path: "/uploads/room4-1.jpg",
        roomId: 4,
      },
      {
        id: 402,
        fileName: "room4-2.jpg",
        url: "https://example.com/images/room4-2.jpg",
        path: "/uploads/room4-2.jpg",
        roomId: 4,
      },
      {
        id: 403,
        fileName: "room4-3.jpg",
        url: "https://example.com/images/room4-3.jpg",
        path: "/uploads/room4-3.jpg",
        roomId: 4,
      },
    ],
  },
  {
    id: 5,
    name: "Эконом",
    description: "Небольшой бюджетный номер",
    capacity: 1,
    price: "1800.00",
    status: "maintenance",
    area: 12,
    Image: [],
  },
  {
    id: 6,
    name: "Бизнес-люкс",
    description: "Номер для деловых поездок с рабочим столом",
    capacity: 2,
    price: "5200.00",
    status: "available",
    area: 30,
    Image: [
      {
        id: 601,
        fileName: "room6-1.jpg",
        url: "https://example.com/images/room6-1.jpg",
        path: "/uploads/room6-1.jpg",
        roomId: 6,
      },
    ],
  },
  {
    id: 7,
    name: "Президентский люкс",
    description: "Эксклюзивный номер высшего класса",
    capacity: 2,
    price: "15000.00",
    status: "available",
    area: 80,
    Image: [
      {
        id: 701,
        fileName: "room7-1.jpg",
        url: "https://example.com/images/room7-1.jpg",
        path: "/uploads/room7-1.jpg",
        roomId: 7,
      },
      {
        id: 702,
        fileName: "room7-2.jpg",
        url: "https://example.com/images/room7-2.jpg",
        path: "/uploads/room7-2.jpg",
        roomId: 7,
      },
    ],
  },
  {
    id: 8,
    name: "Номер с видом на море",
    description: "Номер с панорамным видом на море",
    capacity: 3,
    price: "6800.00",
    status: "booked",
    area: 45,
    Image: [
      {
        id: 801,
        fileName: "room8-1.jpg",
        url: "https://example.com/images/room8-1.jpg",
        path: "/uploads/room8-1.jpg",
        roomId: 8,
      },
    ],
  },
  {
    id: 9,
    name: "Мансарда",
    description: "Романтичный номер на верхнем этаже",
    capacity: 2,
    price: "4900.00",
    status: "available",
    area: 28,
    Image: [],
  },
  {
    id: 10,
    name: "Студия",
    description: "Номер с мини-кухней для длительного проживания",
    capacity: 2,
    price: "5500.00",
    status: "available",
    area: 38,
    Image: [
      {
        id: 1001,
        fileName: "room10-1.jpg",
        url: "https://example.com/images/room10-1.jpg",
        path: "/uploads/room10-1.jpg",
        roomId: 10,
      },
      {
        id: 1002,
        fileName: "room10-2.jpg",
        url: "https://example.com/images/room10-2.jpg",
        path: "/uploads/room10-2.jpg",
        roomId: 10,
      },
    ],
  },
];
